// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account/account.proto

package com.aurora.proto.account;

public final class AccountProto {
  private AccountProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025account/account.proto\022\007account\032\022utils/" +
      "common.proto2E\n\007Account\022:\n\010accounts\022\026.ut" +
      "ils.AccountsRequest\032\024.utils.AccountsRepl" +
      "y\"\000B(\n\030com.aurora.proto.accountB\014Account" +
      "Protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.aurora.proto.utils.CommonProto.getDescriptor(),
        }, assigner);
    com.aurora.proto.utils.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
